# site settings for MiniWeb

index:
- index.html
- index.md
- index.txt

autoindex: true

markdown:
  script:
  - /script.js
  style:
  - /style.css
  style_code: |-
    body {
      //max-width: 480px;
    }
  script_code: |-
    greeting("world");
